name: tests

on: ['push', 'pull_request']

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-22.04, windows-2019]
        php: [8.1, 8.2, 8.3]
        laravel: [^10.18, ^11.0]
        stability: [prefer-lowest, prefer-stable]
        include:
          - laravel: ^10.18
            testbench: ^8.7
          - laravel: ^11.0
            testbench: ^9.0
        exclude:
          - laravel: ^11.0
            os: windows-2019
          - laravel: ^11.0
            php: 8.1

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: fileinfo
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute lint tests with Laravel preset
        run: vendor/bin/pint --test

      - name: Execute static analysis
        run: vendor/bin/phpstan
        if: matrix.php == '8.1'

      - name: Execute unit/feature tests
        run: vendor/bin/phpunit
